### ISSUE TITLE
Changing default "organization member" permissions to "None", giving "core-devs" admin on all public repos

### ISSUE THREAD

**Issue by ryan-williams** [zarr-developers/governance#10]
The @zarr-developers/steering-council is interested in using GitHub to store and collaborate on private documents (e.g. contracts and legal documents related to [our CZI funding](https://chanzuckerberg.com/eoss/proposals/scalable-storage-of-tensor-data-for-scientific-computing/)).

The best way to get the access topology we want appears to involve:
- [x] create @zarr-developers/core-devs team, including all organization members, for easy restoration of "admin" permissions to repos
- [x] give @zarr-developers/core-devs "admin" permissions on all public repos ([notebook](https://gist.github.com/ryan-williams/7be1769599557082284372c7b61dccb8))
- [x] set "base member privileges" in [the zarr-developers organization](https://github.com/zarr-developers) to "None"
  - (org members are all in `core-devs`, and thus retain admin permissions on all public repos)

**This set of steps shouldn't change anyones' access to [repositories under zarr-developers](https://github.com/zarr-developers)**.

The main downside seems to be that, going forward, new-repo creators will need to give "admin" rights to the `core-devs` team. Consensus on @zarr-developers/steering-council is that that's worth the streamlining of our processes. I also believe this is an established pattern for leveraging GH Teams for access-control.

I plan to complete the final step above tomorrow. If some assumption is wrong and it does change anyones' access in an undesired way, we can always revert. Comments welcome!

**Comment by alimanfoo** [comment]
OK by me.

**Comment by ryan-williams** [comment]
I finally did this. Please holler if something seems off.

**Comment by jakirkham** [comment]
Thanks Ryan! 😄

**Comment by joshmoore** [comment]
Note: this got a pretty big overall via https://github.com/zarr-developers/governance/pull/17 in preparation for the implementation council.
