### ISSUE TITLE
Invitation to Zarr Implementation Council (zarr-python)

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/governance#19]
_attn:_ @zarr-developers/python-core-devs 

## Introduction

Changes to the Zarr specification impact all implementors. In order to manage
that burden, the Zarr project has formed an implementation council. Each
implementation community selects one person to sit on the council to help shape
changes to the Zarr spec.

## Rights & Responsibilities

The hope is that sitting on the council is itself a minimal additional burden.
Each decision to be made will be encapsulated as a "ZEP" (Zarr Enhancement
Process) which will need to be voted on. Each community can state that they
intend to actively implement ("YES") that they might eventually implement
("ABSTRAIN") or that they will never implement ("VETO").

Members of the Implementation Council will be added to the similarly named
team on GitHub which has privileges on the zarr-specs and zep repos.

## Next steps

First, if you would like to read more on the council and the process surrounding it,
please see the [Governance document](https://github.com/zarr-developers/governance/blob/74d6f3fcd98ee76c5807d0f8754a195a3ce18876/GOVERNANCE.md#implementation-council) as well as the [ZEP](https://github.com/zarr-developers/governance/blob/1d2f3989896955c8bff8dc8d3d03f7580eaa474e/ZEP/instructions/zep0000.md) itself for more information.

Then, please use this issue to let the steering council know either:
 * that you are not interested or perhaps do not have the capacity at this time
 * or whom you will be assigning as your council representative.

If any help or discussion is needed, feel free to do so here or link to other
issues/threads as necessary.

Finally, we invite any implementation that has joined the Implementation
Council to also host their implementation's repositories in the zarr-developers
GitHub organization. This is not mandatory and has no impact on voting rights.
Most importantly, we would like to show the vibrancy of the Zarr community
and the strength that comes from a larger number of implementations.

Thanks to all of you!

----

* If joining:
  * [x] Create a dedicated core-devs team and assign all members
  * [x] Add representative to the implementation-council team
  * [x] Update GOVERNANCE.md
  * [x] N/A ~Accept transfer of repository if desired~

**Comment by jni** [comment]
I *am* interested but I don't have the bandwidth to participate. I might still lurk a bit. 😊  Thank you!!!

**Comment by axtimwalde** [comment]
I am interested to represent n5-zarr and will try to find a free week to read through all the documents soon.

**Comment by jakirkham** [comment]
> I am interested to represent n5-zarr and will try to find a free week to read through all the documents soon.

That would be great Stephan! 😄

There's an invitation for n5-zarr here ( https://github.com/zarr-developers/governance/issues/25 ) 🙂

**Comment by joshmoore** [comment]
I actioned @axtimwalde's sentiment on #25. :+1: Also thanks @jni for the interest (and lurkers always welcome). Probably this invite is the most interesting one. Is there anyone in python-core-devs and not on the steering-council that _would be_ interested?

**Comment by jakirkham** [comment]
> Probably this invite is the most interesting one. Is there anyone in python-core-devs and not on the steering-council that _would be_ interested?

My guess is you and I are the most active here. 😄 Agree it is not ideal to have these lines blurred in this way, but it is likely impractical to do anything else atm. Would be nice to see that change in the future (if for no other reason than to get one thing off our plates 😉). Perhaps having v3 adoption in zarr-python will make it more interesting for new contributors, who could serve this role in the future 🙂

**Comment by joshmoore** [comment]
Zarr-python itself will need a process in place regarding how we run nominations, etc. (see https://github.com/zarr-developers/governance/issues/31) But knowing that we don't have that at the moment, and zarr-python still hasn't joined the ZIC (🙀) the ZSC discussed yesterday and would propose @grlee77 due to his work on the V3 implementation. Speaking for @grlee77, he would be willing to take on the role but as most of us is aware of time constraints. If there is no one else who would like to step forward and there are no objections, I'll add Greg to the ZIC next week. The new process will have a review built in so all of the many of you who want a chance will get it. :smile:

**Comment by joshmoore** [comment]
Welcome, @grlee77.
