### ISSUE TITLE
Invitation to Zarr Implementation Council (netcdf)

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/governance#21]
_attn:_ @dennisheimbigner @haileyajohnson @WardF @unidata

## Introduction

Changes to the Zarr specification impact all implementors. In order to manage
that burden, the Zarr project has formed an implementation council. Each
implementation community selects one person to sit on the council to help shape
changes to the Zarr spec.

## Rights & Responsibilities

The hope is that sitting on the council is itself a minimal additional burden.
Each decision to be made will be encapsulated as a "ZEP" (Zarr Enhancement
Process) which will need to be voted on. Each community can state that they
intend to actively implement ("YES") that they might eventually implement
("ABSTRAIN") or that they will never implement ("VETO").

Members of the Implementation Council will be added to the similarly named
team on GitHub which has privileges on the zarr-specs and zep repos.

## Next steps

First, if you would like to read more on the council and the process surrounding it,
please see the [Governance document](https://github.com/zarr-developers/governance/blob/74d6f3fcd98ee76c5807d0f8754a195a3ce18876/GOVERNANCE.md#implementation-council)
as well as the [ZEP](https://github.com/zarr-developers/governance/blob/1d2f3989896955c8bff8dc8d3d03f7580eaa474e/ZEP/instructions/zep0000.md) itself for more information.

Then, please use this issue to let the steering council know either:
 * that you are not interested or perhaps do not have the capacity at this time
 * or whom you will be assigning as your council representative.

If any help or discussion is needed, feel free to do so here or link to other
issues/threads as necessary.

Finally, we invite any implementation that has joined the Implementation
Council to also host their implementation's repositories in the zarr-developers
GitHub organization. This is not mandatory and has no impact on voting rights.
Most importantly, we would like to show the vibrancy of the Zarr community
and the strength that comes from a larger number of implementations.

Thanks to all of you!

----

* If joining:
  * [ ] Create a dedicated core-devs team and assign all members
  * [ ] Add representative to the implementation-council team
  * [ ] Update GOVERNANCE.md
  * [ ] Accept transfer of repository if desired

**Comment by WardF** [comment]
Not sure how this slipped past; I've been out is the office, but I expect we will be participating. I'll take a closer look at this tomorrow morning :). Thanks!

**Comment by jakirkham** [comment]
FWIW Dennis mentioned interest in participating in comment ( https://github.com/zarr-developers/governance/issues/24#issuecomment-1121526822 ).

**Comment by joshmoore** [comment]
Thanks, all, for the positive response! Very much looking forward to it. Who shall we list as the primary contact in https://github.com/zarr-developers/governance/blob/master/GOVERNANCE.md#zarr-implementation-council-zic ?

**Comment by joshmoore** [comment]
see https://github.com/zarr-developers/governance/issues/24#issuecomment-1132608842

At the community meeting this week, @WardF accepted the role for both netcdf-c and netcdf-java. This issue has been updated to reference simply the "netcdf" implementation, and we can review this in the coming months, years, etc...

Welcome @unidata

**Comment by DennisHeimbigner** [comment]
I will accept this invitation, thank you. If it becomes too much of a 
burden,
I will let you know.
=Dennis Heimbigner
   Unidata
