### ISSUE TITLE
Invitation to Zarr Implementation Council (jzarr)

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/governance#29]
_attn:_ @SabineEmbacher @forman @bcdev

## Introduction

Changes to the Zarr specification impact all implementors. In order to manage
that burden, the Zarr project has formed an implementation council. Each
implementation community selects one person to sit on the council to help shape
changes to the Zarr spec.

## Rights & Responsibilities

The hope is that sitting on the council is itself a minimal additional burden.
Each decision to be made will be encapsulated as a "ZEP" (Zarr Enhancement
Process) which will need to be voted on. Each community can state that they
intend to actively implement ("YES") that they might eventually implement
("ABSTRAIN") or that they will never implement ("VETO").

Members of the Implementation Council will be added to the similarly named
team on GitHub which has privileges on the zarr-specs and zep repos.

## Next steps

First, if you would like to read more on the council and the process surrounding it,
please see the [Governance document](https://github.com/zarr-developers/governance/blob/74d6f3fcd98ee76c5807d0f8754a195a3ce18876/GOVERNANCE.md#implementation-council)
as well as the [ZEP](https://github.com/zarr-developers/governance/blob/1d2f3989896955c8bff8dc8d3d03f7580eaa474e/ZEP/instructions/zep0000.md) itself for more information.

Then, please use this issue to let the steering council know either:
 * that you are not interested or perhaps do not have the capacity at this time
 * or whom you will be assigning as your council representative.

If any help or discussion is needed, feel free to do so here or link to other
issues/threads as necessary.

Finally, we invite any implementation that has joined the Implementation
Council to also host their implementation's repositories in the zarr-developers
GitHub organization. This is not mandatory and has no impact on voting rights.
Most importantly, we would like to show the vibrancy of the Zarr community
and the strength that comes from a larger number of implementations.

Thanks to all of you!

----

* If joining:
  * [ ] Create a dedicated core-devs team and assign all members
  * [ ] Add representative to the implementation-council team
  * [ ] Update GOVERNANCE.md
  * [ ] Accept transfer of repository if desired

**Comment by forman** [comment]
Hi @joshmoore, thanks for the invitation, it is an honour!  :)

Despite its generic name, we are developing jzarr mainly for the use cases we have in our (small) company. However, any Zarr feature we required, has so far been implemented conforming the Zarr 2.0 Spec.
 
Before we can consent to a seat in the council, we'd like to better understand what effort is associated with that responsibility. In addition, we don't want to slowdown the evolution of Zarr by voting against some ZEPs, only because we (currently) don't have the time to implement them in jzarr.

Could you please give us a hint about the desired effort and frequency/duration of the envisaged meetings?

**Comment by joshmoore** [comment]
Hi @forman, thanks for your feedback & opennes: we definitely understand the balance with our day jobs.

In the short-term, there are likely be a number of decisions to be made around the migration to v3:
 * the definition of v3 itself (https://github.com/zarr-developers/zarr-specs/issues/140)
 * then the addition of sharding (https://github.com/zarr-developers/zarr-specs/issues/127)
 * likely following by several other breaking issues:
   - variable chunking: https://github.com/zarr-developers/zarr-specs/issues/138
   - other data types: https://github.com/zarr-developers/zarr-specs/issues/131, https://github.com/zarr-developers/zarr-specs/issues/130
   - and similar.

though we certainly expect the frequency to reduce once the initial bulk of work has been decided.

To the extent that you & @bcdev would like to be actively involved in v3's definition, then this would be a good time to join with an eye on what it would mean for jzarr to implement the new spec(s).

However, if you decide that that's too much involvement for the moment, that doesn't preclude your joining in the future (once the air has cleared :smile:).

**Comment by joshmoore** [comment]
@forman @SabineEmbacher: any thoughts to the above or would it be best to close this for the moment?

**Comment by SabineEmbacher** [comment]
Dear @joshmoore,

It's really hard to say no.
But a "yes" that we cannot keep would not help anyone.
We are sorry! 🙁

**Comment by joshmoore** [comment]
@SabineEmbacher & @forman, thanks for the definitive answer. I'm sure it wasn't an easy decision, but do let us know if anything changes.

All the best,
~Josh
