### ISSUE TITLE
Define how core-members may be removed when they become inactive

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/governance#38]
The core-developer guide describes how to add new core developers but fails to address what to do when members become inactive. 

https://github.com/zarr-developers/governance/blob/b1c414c39786fd801303aae7e56c65f028280cf9/CORE_DEV_GUIDE.md?plain=1#L157-L169

I would like to suggest some kind of trigger by which fully-inactive members can be removed from the core-developer roster of zarr projects. An example could be:

> If a Core Developer becomes inactive in The Project for a period of one year, they will be considered for removal from the Project Core Developer Team.

cc @zarr-developers/python-core-devs, @zarr-developers/steering-council 

xref: https://github.com/zarr-developers/zarr-python/discussions/1608

**Comment by rabernat** [comment]
Sounds good to me! Every open source project needs a mechanism to rotate inactive developers off.
