### ISSUE TITLE
Spec development process

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/governance#4]
Raising this to cross-reference an issue I raised on the zarr-specs repo: https://github.com/zarr-developers/zarr-specs/issues/13. It's probably easiest to discuss it there on the zarr-specs repo, but it is part of the governance model so raising here for visibility.

See also https://github.com/zarr-developers/zarr-specs/pull/12 which starts work towards a document describing the spec development process.

**Comment by MSanKeys963** [comment]
I think this is achieved by the [ZEP](https://zarr.dev/zeps) process. Can we close this?
CC: @joshmoore
