### ISSUE TITLE
CZI Essential Open-Source Software RFA

### ISSUE THREAD

**Issue by ryan-williams** [zarr-developers/governance#6]
I started filling out the application at https://apply.chanzuckerberg.com/.

I don't see an easy way to collaborate on it, so I put what I have so far in [this gdoc](https://docs.google.com/document/d/1nkuvXemo2WDDrLxPc5R7ojzBObIVx-Ifs8sZVTHzbT4/edit?usp=sharing) (a blank template gdoc is [here](https://docs.google.com/document/d/1lLL-UJslLxvS8bpEyNJWuK1Qk_pCQuianvDeuDs6OFI/edit?usp=sharing), fwiw).

That link gives comment permissions; let me know if you want edit permissions (I added a few members of @zarr-developers/core-devs I've already discussed this directly with).

I left "TODO" comments on all the parts that need filling out or expanding. In particular, [the actual body of the proposal is currently empty](https://docs.google.com/document/d/1nkuvXemo2WDDrLxPc5R7ojzBObIVx-Ifs8sZVTHzbT4/edit#heading=h.gca21hofcno7), I've just filled out some light copy and boilerplate info in other sections.

A big thing that needs to happen in parallel is NumFOCUS fiscal sponsorship (#7).

**Comment by ryan-williams** [comment]
I think this is superceded by https://github.com/zarr-developers/community/issues/22

**Comment by alimanfoo** [comment]
Again apologies for missing this issue, I lost track of what was where.
