### ISSUE TITLE
Apply for NumFOCUS fiscal sponsorship

### ISSUE THREAD

**Issue by ryan-williams** [zarr-developers/governance#7]
Per https://github.com/zarr-developers/community/issues/12 and https://github.com/zarr-developers/zarr-python/issues/400, we should try to make Zarr a NumFOCUS project.

For #6, we want to be "fiscally sponsored" in the "grantor/grantee" model, not just "affiliated", by my reading of [NumFOCUS docs](https://numfocus.org/information-fiscal-sponsorship).

Links:
* [process doc](https://docs.google.com/document/d/12KGmSD_EGWqlzh0fiaHNIiN6xPWgdTy--NYf4QR-5k8/edit)
* [application doc](https://docs.google.com/document/d/1-MwAqOir5vf4FAhREPj80Ynv-SKugSaN5mZcIHUIsug/edit)

> If your project is interested in applying for NumFOCUS Fiscal Sponsorship or would like additional information, please email us at admin@numfocus.org to set up a call with our Executive Director.

I'll start filling out the above docs today, and reach out to them directly.

cc @zarr-developers/core-devs

**Comment by ryan-williams** [comment]
superceded by https://github.com/zarr-developers/community/issues/21

**Comment by alimanfoo** [comment]
Thanks @ryan-williams, sorry I knew I had seen this issue somewhere before but couldn't remember where :-)
